update sh

diff --git a/ethereum/templates/geth-miner-deployment.yaml b/ethereum/templates/geth-miner-deployment.yaml
--- a/ethereum/templates/geth-miner-deployment.yaml
+++ b/ethereum/templates/geth-miner-deployment.yaml
@@ -69,18 +69,22 @@ spec:
             - "-c"
             - |-
               apk add --no-cache curl; 
-              CNT=0; 
-              echo "retrieving bootnodes from $BOOTNODE_REGISTRAR_SVC" while [ $CNT -le 90 ] do curl -m 5 -s $BOOTNODE_REGISTRAR_SVC | xargs echo -n >> /geth/bootnodes; 
-              if [ -s /geth/bootnodes ] 
-                then cat /geth/bootnodes; 
-                exit 0; 
-              fi; 
-              echo "no bootnodes found. retrying $CNT..."; 
-              sleep 2 || break; 
-              CNT=$((CNT+1)); 
-              done; 
-              echo "WARNING. unable to find bootnodes. continuing but geth may not be able to find any peers."; 
-              exit 0; 
+              CNT=0;
+              echo "retrieving bootnodes from $BOOTNODE_REGISTRAR_SVC"
+              while [ $CNT -le 90 ] 
+              do
+                curl -m 5 -s $BOOTNODE_REGISTRAR_SVC | xargs echo -n >> /geth/bootnodes;
+                if [ -s /geth/bootnodes ] 
+                then
+                  cat /geth/bootnodes;
+                  exit 0;
+                fi;
+                echo "no bootnodes found. retrying $CNT..."; 
+                sleep 2 || break;
+                CNT=$((CNT+1));
+              done;
+              echo "WARNING. unable to find bootnodes. continuing but geth may not be able to find any peers.";
+              exit 0;
           env: 
             - name: BOOTNODE_REGISTRAR_SVC 
               value: bootnode-registrar 
