update yaml

diff --git a/ethereum/templates/geth-miner-deployment.yaml b/ethereum/templates/geth-miner-deployment.yaml
--- a/ethereum/templates/geth-miner-deployment.yaml
+++ b/ethereum/templates/geth-miner-deployment.yaml
@@ -80,19 +80,19 @@ spec:
           command: ["/bin/sh"]
           args:
             - "-c"
-            - |
-            apk add --no-cache curl; 
-            CNT=0; 
-            echo "retrieving bootnodes from $BOOTNODE_REGISTRAR_SVC" while [ $CNT -le 90 ] do curl -m 5 -s $BOOTNODE_REGISTRAR_SVC | xargs echo -n >> /geth/bootnodes; 
-            if [ -s /geth/bootnodes ] then cat /geth/bootnodes; 
-            exit 0; 
-            fi; 
-            echo "no bootnodes found. retrying $CNT..."; 
-            sleep 2 || break; 
-            CNT=$((CNT+1)); 
-            done; 
-            echo "WARNING. unable to find bootnodes. continuing but geth may not be able to find any peers."; 
-            exit 0; 
+            - |-
+              apk add --no-cache curl; 
+              CNT=0; 
+              echo "retrieving bootnodes from $BOOTNODE_REGISTRAR_SVC" while [ $CNT -le 90 ] do curl -m 5 -s $BOOTNODE_REGISTRAR_SVC | xargs echo -n >> /geth/bootnodes; 
+              if [ -s /geth/bootnodes ] then cat /geth/bootnodes; 
+              exit 0; 
+              fi; 
+              echo "no bootnodes found. retrying $CNT..."; 
+              sleep 2 || break; 
+              CNT=$((CNT+1)); 
+              done; 
+              echo "WARNING. unable to find bootnodes. continuing but geth may not be able to find any peers."; 
+              exit 0; 
           env: 
             - name: BOOTNODE_REGISTRAR_SVC 
               value: bootnode-registrar 
@@ -102,6 +102,6 @@ spec:
       volumes: 
         - name: data 
           emptyDir: {} 
-      - name: config 
-        configMap: 
-          name: eth-geth
+        - name: config 
+          configMap: 
+            name: eth-geth
